- HOW_TO_PARTICIPATE.MD
I tried to correct few sentences and style of presentation.
Thank you
> Grammatical corrections

- Python/Bubble-Sort-algo.py
>  Bubble-Sort-algo.py

- Python/handcricket.py
Added a new command line Hand Cricket game(i do appologise if i have done something wrong. this is second ever time using github)
> First Commit

- Python/even-odd.py
Added a program that can identify if the number passed as an argument is even or odd
> even-odd.py

- Python/insertionsort.py
The insertion sort algorithm coded in python and requested to merge.
> Added insertion sort program

- Python/musicPlayer.py
- Python/screenRecorder.py
this is a simple screen recorder in Python that you can further extend to your own needs.
> screen recorder with python

- Python/reverse palindrome.py
- Python/sum of square of n natural number.py
> Alternative approaches

- Python/Prime Number From Digit Words.py
The input is added as a word. For example "ninety nine", which is converted to 99 and all the prime numbers till that is found and printed.
> Added Prime Number From Digit Words

- Python/Binary_Tree_algo.py
> Binary_Tree_algo.py

- Python/BasicCalculator.py
Now the program doesn't throws an error if we choose second number as 0 in division function
> Fixed the zero division error in BasicCalaulator.py

- Python/Base Convertor Number System.py
Added Base Convertor in Number System. Please merge my PR and help me contribute open source.
> Added base convertor python file

- Python/TowerOfHanoi.py
Added Solution to Tower of Hanoi in Python.
Issue #38
> Added Tower of Hanoi Program in Python as per (Issue #38)

- README.md
> Fixed typos in the readme.md file.

- Python/Fizz-Buzz-Challenge.py
This is a common interview question. Here you have to print FizzBuzz if the input value is devisable by 3 and 5. 
Or if it is devisable by only 3, print Fizz. 
If it is devisable by only 5, print Buzz
> Fizz-Buzz-Challenge famous interview question and answer added in python

- Python/possible_combination_from_digits.py
The Python Program to accept three distinct digits and prints all possible combinations from the digits.
```
Case 1:
Enter first number:1
Enter second number:2
Enter third number:3
1 2 3
1 3 2
2 1 3
2 3 1
3 1 2
3 2 1
Case 2:
Enter first number:5
Enter second number:7
Enter third number:3
5 7 3
5 3 7
7 5 3
7 3 5
3 5 7
3 7 5
```
> Add algorithm to fetch possible combination from 3 digits.

- Python/DecimalToBinary.py
Hi There!
i'm adding python code for Decimal to Binary conversion
> Added DecimalToBnary

- HOW_TO_PARTICIPATE.MD
#learnt the trick by reading your content and found the mistake #thanks #hacktoberfest
> updated some change

- Python/dice_roller.py
A simple python multi side dice roller
> Added a python dice roller

- Python/BasicCalculator.py
Please review and consider adding it
> Added Sqrt , factorial,sine , cosine and tan

- Python/urlShortner.py
Added basic code of Url shortner
> Basic code of Url shortner

- Python/face_recognition_using_keyword.py
In order for this project to work you need to have a xml file which u can get from [here](https://github.com/opencv/opencv/blob/master/data/haarcascades/haarcascade_frontalface_default.xml) and a zip file in which you have a number of png images with text and faces in them.
> Face Recognition Project Using a Keyword
